// Ensure you run: npm install jspdf jspdf-autotable
import { jsPDF } from "jspdf";
import 'jspdf-autotable';

export const generatePurchaseOrderPDF = (orderData) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185); // Blue
  doc.text("FreshStock AI - Purchase Order", 14, 22);
  
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Order ID: ${orderData.id}`, 14, 30);
  doc.text(`Date: ${orderData.date}`, 14, 36);
  doc.text(`Generated by: AI Forecast Engine`, 14, 42);

  // Table
  const tableColumn = ["Product", "Predicted Requirement", "Unit Price (Est)", "Total"];
  const tableRows = [];

  let grandTotal = 0;
  orderData.items.forEach(item => {
    const total = item.qty * item.price;
    grandTotal += total;
    tableRows.push([item.name, `${item.qty} kg/L`, `INR ${item.price}`, `INR ${total}`]);
  });

  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 50,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] }
  });

  // Footer Total
  const finalY = doc.lastAutoTable.finalY || 50;
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Grand Total: INR ${grandTotal}`, 14, finalY + 10);

  // Save the PDF
  doc.save(`${orderData.id}_Forecast_PO.pdf`);
};
